name: Publish

on:
  push:
    tags:
        - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Build
        run: |
          npm ci
          npm run build
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          tags: teranovalp/http-catch-all:${{ env.CI_REF_NAME }}
          push: true
          context: .
      - uses: docker/build-push-action@v2
        with:
          tags: teranovalp/http-catch-all:latest
          push: true
          context: .
